# GET http://localhost:3000/api/userboards

# ###

# GET http://localhost:3000/api/userboards
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTA5NTk2MDk4Nzk4ODk5MjkyODk5IiwidXNlcl9lbWFpbCI6InN1Z2FyZ2xpZGVyMjIyMkBnbWFpbC5jb20iLCJ1c2VyX3BpYyI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBVFhBSndKSEdEeXlvLTNiN28tYnc4ZEgwN3RKelM2VU9pY2pmRXF0SUJxPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IlRzemlseSIsImlhdCI6MTYyNzkwNzkzMX0.elIK-4iLX8Rzh9vQsJOu10dvuKjfUZxh7UN9BeIqyqo

# ##
# POST http://localhost:5000/api/appointment
# Content-Type: application/json

# { "startDate": "2023-10-02",
#     "startTime": "18:05",
#     "endDate": "2023-10-02",
#     "endTime": "18:07",
#     "comment": "tesztcomment2"}

GET http://localhost:3000/api/private

###

GET http://localhost:3000/api/private
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTA5NTk2MDk4Nzk4ODk5MjkyODk5IiwidXNlcl9lbWFpbCI6InN1Z2FyZ2xpZGVyMjIyMkBnbWFpbC5jb20iLCJ1c2VyX3BpYyI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBVFhBSndKSEdEeXlvLTNiN28tYnc4ZEgwN3RKelM2VU9pY2pmRXF0SUJxPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IlRzemlseSIsImlhdCI6MTYyODE2MjA2MH0.jet6xlLPX6rhthwZLVo763tgoHGVPERwhEfuyWihQEk
